version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/meetup-pulse
    steps:
      - checkout
      - restore_cache:
          keys:
          - py-dependencies-{{ checksum "api-server/Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv
            export PIPENV_VENV_IN_PROJECT=~/meetup-pulse/api-server
            cd api-server
            pipenv install --dev
      - save_cache:
          paths:
            - ./api-server/.venv
          key: py-dependencies-{{ checksum "api-server/Pipfile.lock" }}
      - run:
          name: Run Static Analysis
          command: |
            cd api-server
            pipenv run flake8
      - run:
          name: Run Tests
          command: |
            cd api-server/api_server
            pipenv run pytest
